FROM golang:1.7
CMD ["./main"]
EXPOSE 3000
RUN mkdir -p /go/src/github.com/openshift-roadshow/cloud-native-katacoda
WORKDIR /go/src/github.com/openshift-roadshow/cloud-native-katacoda
ADD . /go/src/github.com/openshift-roadshow/cloud-native-katacoda
RUN go get && go build -a -installsuffix cgo -o main .
